server:
  port: 7355
spring:
  application:
    name: richz-project
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/sk?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      filters: stat, wall, log4j
      # 其他 Druid 配置

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    mapper-locations: classpath*:mapper/*Mapper.xml
    config-location: classpath:mybatis-config.xml
    type-aliases-package: com.richz.frame.entity, com.richz.frame.entity.vo
# 日志配置
logging:
  level:
      com.richz.frame: debug
      org.springframework: warn
      org.apache.ibatis: debug
      com.baomidou.mybatisplus: debug
